In [2]:
import numpy as np
from hmmlearn import hmm

In [3]:
states = ["box 1", "box 2", "box3"]
n_states = len(states)

In [4]:
observations = ["red", "white"]
n_observations = len(observations)

In [5]:
start_probability = np.array([0.2, 0.4, 0.4])

transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])

emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])


In [6]:
model = hmm.MultinomialHMM(n_components=n_states)

model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


In [37]:
seen = np.array([[0,1,0]]).T

In [38]:
# Reshape the seen array to have the correct shape
# seen = np.array([[0, 1]])

# Predict the hidden states
box2 = model.predict(seen)
print(np.array(states)[box2])

ValueError: Size of each quantile should be size of p: received 1, but expected 2.

In [45]:
model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)
X2 = np.array([[0,1,0,1],[0,0,0,1],[1,0,1,1]])
model2.fit(X2)

print ('startprob_',model2.startprob_)
print ('-----------------------------------------')
print ('transmat_',model2.transmat_)
print ('-----------------------------------------')
print ('emissionprob_',model2.emissionprob_)
print ('-----------------------------------------')
print ('score',model2.score(X2))

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340
Fitting a model with 17 free scalar parameters with only 12 data points will result in a degenerate solution.


startprob_ [0. 1. 0.]
-----------------------------------------
transmat_ [[4.94065646e-324 0.00000000e+000 1.00000000e+000]
 [9.97453065e-001 8.26159862e-011 2.54693494e-003]
 [0.00000000e+000 0.00000000e+000 1.00000000e+000]]
-----------------------------------------
emissionprob_ [[4.47380661e-185 0.00000000e+000 4.47380661e-185 1.00000000e+000]
 [0.00000000e+000 5.00000000e-001 0.00000000e+000 5.00000000e-001]
 [3.33050581e-001 0.00000000e+000 3.33050581e-001 3.33898839e-001]]
-----------------------------------------
score -2.1989246918578833
