In [1]:
import numpy as np
from hmmlearn import hmm
#http://hmmlearn.readthedocs.io/en/latest/

隐藏状态：3个盒子

In [2]:
states = ["box 1", "box 2", "box3"]
n_states = len(states)

观测状态：2种球

In [3]:
observations = ["red", "white"]
n_observations = len(observations)

模型参数

In [4]:
start_probability = np.array([0.2, 0.4, 0.4])

transition_probability = np.array([
  [0.5, 0.2, 0.3],
  [0.3, 0.5, 0.2],
  [0.2, 0.3, 0.5]
])

emission_probability = np.array([
  [0.5, 0.5],
  [0.4, 0.6],
  [0.7, 0.3]
])


In [5]:
#用于离散观测状态
model = hmm.MultinomialHMM(n_components=n_states)

model.startprob_=start_probability
model.transmat_=transition_probability
model.emissionprob_=emission_probability

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


### 维特比算法，看到的是[0,1,0]

In [11]:
seen = np.array([[0,1,0]])

In [13]:
logprob, box = model.decode(seen, algorithm="viterbi")


ValueError: n_trials must be set

得到的结果跟我们算的是一样的

In [14]:
print (np.array(states)[box])

NameError: name 'box' is not defined

predict也可以

In [15]:
box2 = model.predict(seen)
print (np.array(states)[box2])

ValueError: n_trials must be set

得到观测序列的概率 ln0.13022≈−2.0385

In [22]:
print (model.score(seen))

-2.03854530992


### EM算法求解模型参数

tol : 停机阈值
n_iter : 最大迭代次数 
n_components : 隐藏状态数目 

In [16]:
model2 = hmm.MultinomialHMM(n_components=n_states, n_iter=20, tol=0.01)
X2 = np.array([[0,1,0,1],[0,0,0,1],[1,0,1,1]])
model2.fit(X2)

print ('startprob_',model2.startprob_)
print ('-----------------------------------------')
print ('transmat_',model2.transmat_)
print ('-----------------------------------------')
print ('emissionprob_',model2.emissionprob_)
print ('-----------------------------------------')
print ('score',model2.score(X2))

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340
Fitting a model with 17 free scalar parameters with only 12 data points will result in a degenerate solution.


startprob_ [1.60531096e-217 1.00000000e+000 1.02967237e-112]
-----------------------------------------
transmat_ [[1.00000000e+000 1.57365326e-184 1.40375490e-027]
 [8.24910275e-006 7.07297370e-014 9.99991751e-001]
 [1.00000000e+000 1.71214820e-188 6.25177302e-032]]
-----------------------------------------
emissionprob_ [[3.33332417e-001 5.35102181e-218 3.33332417e-001 3.33335166e-001]
 [3.85674472e-125 5.00000000e-001 3.85674472e-125 5.00000000e-001]
 [4.35789161e-029 1.02968087e-112 4.35789161e-029 1.00000000e+000]]
-----------------------------------------
score -2.1972300767608073
